version: '3.8'

services:
  postgres:
      image: postgres:16.2
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=trains
      logging:
        options:
          max-size: 10m
          max-file: '3'
      ports:
        - '5434:5432'
      volumes:
        - ./storage/postgres-data:/var/lib/postgresql/data
